// This file was generated by dtk-settings-tools version 0.1.2

#include <DSettings>

void GenerateSettingTranslate()
{
    auto base_close_window_radiogroupText0 = QObject::tr("Minimize to system tray");
    auto base_close_window_radiogroupText1 = QObject::tr("Exit");
    auto base_close_window_radiogroupText2 = QObject::tr("Ask me always");
    auto group_baseName = QObject::tr("Basic");
    auto group_base_close_windowName = QObject::tr("Close Main Window");
}
